INSERT INTO `ppm_ord_function` (`id`, `name`, `code`, `type`) VALUES ('1', '敏捷迭代数限制', 'FunctionAgile', '0');
INSERT INTO `ppm_ord_function` (`id`, `name`, `code`, `type`) VALUES ('2', '任务数限制', 'FunctionTaskLimit', '0');
INSERT INTO `ppm_ord_function` (`id`, `name`, `code`, `type`) VALUES ('3', '项目数限制', 'FunctionProjectCreate', '0');
INSERT INTO `ppm_ord_function` (`id`, `name`, `code`, `type`) VALUES ('4', '归档任务栏', 'FunctionArchiveProjectObjectType', '0');
INSERT INTO `ppm_ord_function` (`id`, `name`, `code`, `type`) VALUES ('5', '自定义筛选', 'FunctionCustomFilter', '0');
INSERT INTO `ppm_ord_function` (`id`, `name`, `code`, `type`) VALUES ('6', '高级筛选', 'FunctionAdvancedFilter', '0');
INSERT INTO `ppm_ord_function` (`id`, `name`, `code`, `type`) VALUES ('7', '自定义字段', 'FunctionCustomField', '0');
INSERT INTO `ppm_ord_function` (`id`, `name`, `code`, `type`) VALUES ('8', '自定义视图', 'FunctionCustomView', '0');
INSERT INTO `ppm_ord_function` (`id`, `name`, `code`, `type`) VALUES ('9', '任务表格', 'FunctionTaskForm', '0');
INSERT INTO `ppm_ord_function` (`id`, `name`, `code`, `type`) VALUES ('10', '文件管理', 'FunctionFileManage', '0');
INSERT INTO `ppm_ord_function` (`id`, `name`, `code`, `type`) VALUES ('11', '统计功能', 'FunctionStatistic', '0');
INSERT INTO `ppm_ord_function` (`id`, `name`, `code`, `type`) VALUES ('12', '回收站', 'FunctionRecycleBin', '0');
INSERT INTO `ppm_ord_function` (`id`, `name`, `code`, `type`) VALUES ('13', '甘特图', 'FunctionGanttChart', '0');
INSERT INTO `ppm_ord_function` (`id`, `name`, `code`, `type`) VALUES ('14', '日历管理', 'FunctionCalendar', '0');
INSERT INTO `ppm_ord_function` (`id`, `name`, `code`, `type`) VALUES ('15', '版本管理', 'FunctionVersionManage', '0');
INSERT INTO `ppm_ord_function` (`id`, `name`, `code`, `type`) VALUES ('16', '测试管理', 'FunctionTestManage', '0');
INSERT INTO `ppm_ord_function` (`id`, `name`, `code`, `type`) VALUES ('17', '归档任务', 'FunctionArchiveTask', '0');

INSERT INTO `ppm_ord_function_level` (`id`, `function_id`, `level`) VALUES ('1', '1', '2');
INSERT INTO `ppm_ord_function_level` (`id`, `function_id`, `level`) VALUES ('2', '2', '2');
INSERT INTO `ppm_ord_function_level` (`id`, `function_id`, `level`) VALUES ('3', '3', '2');
INSERT INTO `ppm_ord_function_level` (`id`, `function_id`, `level`) VALUES ('4', '4', '2');
INSERT INTO `ppm_ord_function_level` (`id`, `function_id`, `level`) VALUES ('5', '5', '2');
INSERT INTO `ppm_ord_function_level` (`id`, `function_id`, `level`) VALUES ('6', '6', '2');
INSERT INTO `ppm_ord_function_level` (`id`, `function_id`, `level`) VALUES ('7', '7', '2');
INSERT INTO `ppm_ord_function_level` (`id`, `function_id`, `level`) VALUES ('8', '8', '2');
INSERT INTO `ppm_ord_function_level` (`id`, `function_id`, `level`) VALUES ('9', '9', '2');
INSERT INTO `ppm_ord_function_level` (`id`, `function_id`, `level`) VALUES ('10', '10', '2');
INSERT INTO `ppm_ord_function_level` (`id`, `function_id`, `level`) VALUES ('11', '11', '2');
INSERT INTO `ppm_ord_function_level` (`id`, `function_id`, `level`) VALUES ('12', '12', '2');
INSERT INTO `ppm_ord_function_level` (`id`, `function_id`, `level`) VALUES ('13', '13', '2');
INSERT INTO `ppm_ord_function_level` (`id`, `function_id`, `level`) VALUES ('14', '14', '2');
INSERT INTO `ppm_ord_function_level` (`id`, `function_id`, `level`) VALUES ('15', '15', '2');
INSERT INTO `ppm_ord_function_level` (`id`, `function_id`, `level`) VALUES ('16', '16', '2');
INSERT INTO `ppm_ord_function_level` (`id`, `function_id`, `level`) VALUES ('17', '17', '2');
