package consts

const (
	//TableIssueTag            = "ppm_pri_issue_tag"
	TableObjectId            = "ppm_bas_object_id"
	TablePayLevel            = "ppm_bas_pay_level"
	TableSourceChannel       = "ppm_bas_source_channel"
	TableOrganization        = "ppm_org_organization"
	TableOrganizationOutInfo = "ppm_org_organization_out_info"
	TableUser                = "ppm_org_user"
	TableUserConfig          = "ppm_org_user_config"
	TableUserOrganization    = "ppm_org_user_organization"
	TableUserOutInfo         = "ppm_org_user_out_info"
	TableIssue               = "ppm_pri_issue"
	//TableIssueDetail                  = "ppm_pri_issue_detail"
	TableIssueRelation           = "ppm_pri_issue_relation"
	TableIssueWorkHours          = "ppm_pri_issue_work_hours"
	TableIssueView               = "ppm_pri_issue_view"
	TableIteration               = "ppm_pri_iteration"
	TableProject                 = "ppm_pro_project"
	TableProjectDetail           = "ppm_pro_project_detail"
	TableProjectRelation         = "ppm_pro_project_relation"
	TableProjectChat             = "ppm_pro_project_chat"
	TableIssueSource             = "ppm_prs_issue_source"
	TableProjectObjectType       = "ppm_prs_project_object_type"
	TableProjectType             = "ppm_prs_project_type"
	TableResource                = "ppm_res_resource"
	TablePermission              = "ppm_rol_permission"
	TablePermissionOperation     = "ppm_rol_permission_operation"
	TableRole                    = "ppm_rol_role"
	TableRoleOperation           = "ppm_rol_operation"
	TableRoleGroup               = "ppm_rol_role_group"
	TableRolePermissionOperation = "ppm_rol_role_permission_operation"
	TableRoleUser                = "ppm_rol_role_user"
	TableShare                   = "ppm_sha_share"
	TableOrgConfig               = "ppm_orc_config"
	TableMessage                 = "ppm_tak_message"
	TableComment                 = "ppm_tre_comment"
	TableTrends                  = "ppm_tre_trends"

	TableIterationStat  = "ppm_sta_iteration_stat"
	TableProjectDayStat = "ppm_sta_project_day_stat"
	TableStatDailyApp   = "lc_stat_daily_app"

	TableDepartment        = "ppm_org_department"
	TableDepartmentOutInfo = "ppm_org_department_out_info"
	TableUserDepartment    = "ppm_org_user_department"

	TableContact                 = "ppm_wst_contact"
	TableTag                     = "ppm_pri_tag"
	TableNotice                  = "ppm_tre_notice"
	TableArea                    = "ppm_cmm_area"
	TableCities                  = "ppm_cmm_cities"
	TableContinents              = "ppm_cmm_continents"
	TableCountries               = "ppm_cmm_countries"
	TableIndustry                = "ppm_cmm_industry"
	TableMobilePrefix            = "ppm_cmm_area"
	TableRegions                 = "ppm_cmm_regions"
	TableStates                  = "ppm_cmm_states"
	TableFolder                  = "ppm_res_folder"
	TableFolderResource          = "ppm_res_folder_resource"
	TableIssueProperty           = "ppm_prs_issue_property"
	TableIterationStatusRelation = "ppm_pri_iteration_status_relation"
	TableOrgFunctionConfig       = "ppm_orc_function_config"

	TableOrgUserLoginRecord = "ppm_org_user_login_record"
	TableUserInvite         = "ppm_org_user_invite"

	TableOrderFs            = "ppm_ord_order_fs"
	TableOrder              = "ppm_ord_order"
	TablePricePlanFs        = "ppm_ord_price_plan_fs"
	TablePricePlanDing      = "ppm_ord_price_plan_ding"
	TableOrderFunction      = "ppm_ord_function"
	TableOrderFunctionLevel = "ppm_ord_function_level"
	TableResourceRelation   = "ppm_res_resource_relation"
	TableRecycleBin         = "ppm_prs_recycle_bin"
	TableOrderDing          = "ppm_ord_order_ding"
	TableBasPayLevel        = "ppm_bas_pay_level"
	TableOrderWeiXin        = "ppm_ord_order_weixin"

	TableCustomField = "ppm_pro_custom_field"

	TableOrgSecret = "ppm_org_secret"

	TableRoleDepartment = "ppm_rol_role_department"

	TableLcApp     = "lc_app"
	TableLcAppView = "lc_app_view"
	//TableLcTodo    = "lc_todo"

	TableLcPerManageGroup       = "lc_per_manage_group"
	TablePrivatizationAuthority = "ppm_org_privatization_authority"
	TablePrivatizationRecords   = "ppm_org_privatization_records"

	TableLabConfig       = "ppm_org_lab_config"
	TableProjectMenu     = "ppm_pro_project_menu_config"
	TableOrgUserLocation = "ppm_org_user_view_location"
)
