#Application:
#  # app 无需执行 db migrate，所以置为 1
#  RunMode: 1
Mysql:
  Host: 192.168.1.163
  Port: 33309
  Usr: root
  Pwd: JoLNCfUX0-7Xgre_W
  Database: polaris_project_manage_appsvc_lctest
Redis:
  Database: 4
Logs:
  Default:
    LogPath: /data/logs/polaris-app/run.log
    Level: debug
  RR:
    LogPath: /data/logs/polaris-app/rr.log
    Level: info
  MQ:
    LogPath: /data/logs/polaris-app/mq.log
    Level: info
Parameters:
  EsIndex:
    Issue: issue_index_test
    Project: project_index_test
    Trends: trends_index_test
