Mysql:
  Host: 47.102.143.45
  Port: 33307
  Usr: pminfo
  Pwd: J3SP*s321&s2~
  Database: polaris_project_manage_test
Redis:
  Database: 3
Logs:
  Default:
    LogPath: ./run.log
    Level: debug
  RR:
    LogPath: ./rr.log
    Level: info
  MQ:
    LogPath: ./mq.log
    Level: info
Parameters:
  EsIndex:
    Issue: issue_index_test
    Project: project_index_test
    Trends: trends_index_test