Mysql:
  # 数据库ip
  Host: mysql.stag.svc.cluster.local
  # 数据库端口
  Port: 3306
  # 数据库用户名
  Usr: root
  # 数据库密码
  Pwd: mysqldev
  # 数据库库名
  Database: polaris_project_manage_commonsvc_stag
Redis:
  # redis ip
  Host: redis.stag.svc.cluster.local
  # redis 端口
  Port: 6379
  # redis 密码
  Pwd:
  # redis 数据库
  Database: 5


MQ:
  Kafka:
    NameServers: kafka.stag.svc.cluster.local