Server:
  Port: 12008

Logs:
  # 默认日志配置
  Default:
    LogPath: /data/logs/polaris-trendssvc/run.log
    # 日志级别
    Level: info
    # 控制台是否输出
    IsConsoleOut: true
    # 单个日志文件大小
    FileSize: 1024
    # 保留日志文件数
    MaxBackups: 20
    # 标签
    Tag: run
  # 输入输出日志
  RR:
    LogPath: /data/logs/polaris-trendssvc/rr.log
    # 日志级别
    Level: info
    # 控制台是否输出
    IsConsoleOut: false
    # 单个日志文件大小
    FileSize: 1024
    # 保留日志文件数
    MaxBackups: 20
    # 标签
    Tag: rr
  # 消息队列日志
  MQ:
    LogPath: /data/logs/polaris-trendssvc/mq.log
    # 日志级别
    Level: info
    # 控制台是否输出
    IsConsoleOut: true
    # 单个日志文件大小
    FileSize: 1024
    # 保留日志文件数
    MaxBackups: 20
    # 标签
    Tag: mq
Sentry:
  Dsn: https://dddf80d560a3459ca3b04401249544fe@sentry.startable.cn/14


Application:
  Name: trendssvc
  Version:
