CREATE TABLE `ppm_res_resource_relation` (
  `id` bigint NOT NULL,
  `org_id` bigint NOT NULL DEFAULT '0',
  `project_id` bigint NOT NULL DEFAULT '0',
  `issue_id` bigint NOT NULL DEFAULT '0',
  `resource_id` bigint NOT NULL DEFAULT '0',
  `source_type` int NOT NULL DEFAULT '0',
  `creator` bigint NOT NULL DEFAULT '0',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updator` bigint NOT NULL DEFAULT '0',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` int NOT NULL DEFAULT '1',
  `is_delete` tinyint NOT NULL DEFAULT '2',
  PRIMARY KEY (`id`),
  KEY `index_ppm_res_resource_relation_org_id` (`org_id`),
  KEY `index_ppm_res_resource_relation_project_id` (`project_id`),
  KEY `index_ppm_res_resource_relation_issue_id` (`issue_id`),
  KEY `index_ppm_res_resource_relation_create_time` (`create_time`),
  KEY `index_ppm_res_resource_relation_creator` (`creator`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
