Application:
  Name: orgsvc
  # 运行模式，1：Saas集群，2：单机部署，3：私有化集群部署，4：私有化单库部署
  # orgsvc 不在进行库的版本比对。所以改为 2。
  RunMode: 2
  Version:
Redis:
  Host: 47.102.143.45
  Port: 26379
  Pwd: sau2Al!tn12
  Database: 4
Mysql:
  Host: 172.19.166.130
  Port: 33309
  Usr: root
  Pwd: JoLNCfUX0-7Xgre_W
  # 数据库库名
  Database: polaris_project_manage_orgsvc_lctest
