Mysql:
  # 数据库库名
  Database: polaris_project_manage_appsvc_uat
Redis:
  Database: 4
MQ:
  Topics:
    IssueTrends:
      Topic: topic_issue_trends_lctest
      GroupId: topic_issue_trends_group_lctest
    ProjectTrends:
      Topic: topic_project_trends_lctest
      GroupId: topic_project_trends_group_lctest
DingTalk:
  SuiteKey: suitejrcjsknkydzg9t4c
  SuiteSecret: xghk9TC3ZyZR2oLUCsVyiqXwoFAvA6IW05qrfygsNv4Da2yYYx04hDV01qN6gn77
  Token: "12345645615313"
  AesKey: "1234567890123456789012345678901234567890123"
  AppId: 75864
  OauthAppId: "dingoayheivmu34mylzrzg"
  OauthAppSecret: "PeQfl0uBtO3VLr-Feix5cIEWM9Oo81Mhec-SRiO2SPiEPU18fg0YZaB7fHXVkX3U"
Parameters:
  EsIndex:
    Issue: issue_index_lctest
    Project: project_index_lctest
    Trends: trends_index_lctest