Mysql:
  Host: 192.168.1.163
  Port: 33309
  Usr: root
  Pwd: JoLNCfUX0-7Xgre_W
  # 数据库库名
  Database: polaris_project_manage_projectsvc_lctest
Nacos:
  Client:
    NamespaceId: "public" #nacos命名空间
    TimeoutMs: 10000 #http请求超时时间，单位毫秒
    ListenInterval: 30000 #监听间隔时间，单位毫秒（仅在ConfigClient中有效）
    BeatInterval: 5000 #心跳间隔时间，单位毫秒（仅在ServiceClient中有效）
    Endpoint: "" #获取nacos节点ip的服务地址
    CacheDir: "cache" #缓存目录
    LogDir: "logs" #日志目录
    UpdateThreadNum: 20 #更新服务的线程数
    NotLoadCacheAtStart: true #在启动时不读取本地缓存数据，true--不读取，false--读取
    UpdateCacheWhenEmpty: true #当服务列表为空时是否更新本地缓存，true--更新,false--不更新
    Username: nacos
    Password: oY4hMsdsqaB06kWK
  Server:
    Server1:
      IpAddr: "172.19.132.101" #nacos服务的ip地址
      Port: 8848 #nacos服务端口
      ContextPath: "/nacos" #nacos服务的上下文路径，默认是“/nacos”
  Discovery:
    GroupName: "DEFAULT_GROUP"
    ClusterName: "DEFAULT"
    Weight: 1
    Enable: false
    Healthy: true
    Ephemeral: true
Redis:
  Host: 172.19.84.54
  Port: 26379
  Pwd: sau2Al!tn12
  Database: 0
  MaxIdleTimeout: 90000

Logs:
  # 默认日志配置
  Default:
    LogPath: /tmp/logs/polaris-projectsvc/run.log
    # 日志级别
    Level: info
    # 控制台是否输出
    IsConsoleOut: true
    # 单个日志文件大小
    FileSize: 1024
    # 保留日志文件数
    MaxBackups: 20
    # 标签
    Tag: run
  # 输入输出日志
  RR:
    LogPath: /tmp/logs/polaris-projectsvc/rr.log
    # 日志级别
    Level: info
    # 控制台是否输出
    IsConsoleOut: false
    # 单个日志文件大小
    FileSize: 1024
    # 保留日志文件数
    MaxBackups: 20
    # 标签
    Tag: rr
  # 消息队列日志
  MQ:
    LogPath: /tmp/logs/polaris-projectsvc/mq.log
    # 日志级别
    Level: info
    # 控制台是否输出
    IsConsoleOut: true
    # 单个日志文件大小
    FileSize: 1024
    # 保留日志文件数
    MaxBackups: 20
    # 标签
    Tag: mq
