CREATE TABLE `ppm_pri_iteration_status_relation` (
  `id` bigint(20) NOT NULL,
  `org_id` bigint(20) NOT NULL DEFAULT '0',
  `project_id` bigint(20) NOT NULL DEFAULT '0',
  `iteration_id` bigint(20) NOT NULL DEFAULT '0',
  `status_id` bigint(20) NOT NULL DEFAULT '0',
  `plan_start_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `plan_end_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `start_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `end_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `creator` bigint(20) NOT NULL DEFAULT '0',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updator` bigint(20) NOT NULL DEFAULT '0',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` int(11) NOT NULL DEFAULT '1',
  `is_delete` tinyint(4) NOT NULL DEFAULT '2',
  PRIMARY KEY (`id`),
  KEY `index_ppm_pri_iteration_status_relation_org_id` (`org_id`),
  KEY `index_ppm_pri_iteration_status_relation_project_id` (`project_id`),
  KEY `index_ppm_pri_iteration_status_relation_iteration_id` (`iteration_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
