CREATE TABLE `ppm_prs_recycle_bin` (
  `id` bigint NOT NULL,
  `org_id` bigint NOT NULL DEFAULT '0',
  `project_id` bigint NOT NULL DEFAULT '0',
  `relation_id` bigint NOT NULL DEFAULT '0',
  `relation_type` bigint NOT NULL DEFAULT '0',
  `ext` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `creator` bigint NOT NULL DEFAULT '0',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updator` bigint NOT NULL DEFAULT '0',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` int NOT NULL DEFAULT '1',
  `is_delete` tinyint NOT NULL DEFAULT '2',
  PRIMARY KEY (`id`),
  KEY `index_ppm_prs_recycle_bin_org_id` (`org_id`),
  KEY `index_ppm_prs_recycle_bin_project_id` (`project_id`),
  KEY `index_ppm_prs_recycle_bin_relation_id` (`relation_id`),
  KEY `index_ppm_prs_recycle_bin_create_time` (`create_time`),
  KEY `index_ppm_prs_recycle_bin_creator` (`creator`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
