CREATE TABLE `ppm_pri_feishu_shortcut` (
  `id` bigint NOT NULL,
  `org_id` bigint NOT NULL DEFAULT '0',
  `tenant_key` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `user_id` bigint NOT NULL DEFAULT '0',
  `out_user_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
	`trigger_key` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '幂等验证',
  `trigger_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `ext` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `project_id` bigint NOT NULL DEFAULT '0',
  `project_object_type_id` bigint NOT NULL DEFAULT '0',
  `event_type` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `creator` bigint NOT NULL DEFAULT '0',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updator` bigint NOT NULL DEFAULT '0',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` int NOT NULL DEFAULT '1',
  `is_delete` tinyint NOT NULL DEFAULT '2',
  PRIMARY KEY (`id`),
  KEY `index_ppm_pri_feishu_shortcut_org_id` (`org_id`),
  KEY `index_ppm_pri_feishu_shortcut_user_id` (`user_id`),
  KEY `index_ppm_pri_feishu_shortcut_project_id` (`project_id`),
  KEY `index_ppm_pri_feishu_shortcut_project_object_type_id` (`project_object_type_id`),
  KEY `index_ppm_pri_feishu_shortcut_trigger_key` (`trigger_key`),
  KEY `index_ppm_pri_feishu_shortcut_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
